---
sidebar: sidebar 
permalink: concept-before-you-begin-to-deploy-gfc.html 
keywords: global file cache, core, edge, management server 
summary: 在您開始在雲端和遠端辦公室部署 BlueXP 邊緣快取之前、您需要注意許多需求。 
---
= 開始部署 BlueXP 邊緣快取之前
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在您開始在雲端和遠端辦公室部署 BlueXP 邊緣快取之前、您需要注意許多需求。



== BlueXP 邊緣快取核心設計考量

視您的需求而定、您可能需要部署一或多個 BlueXP 邊緣快取核心執行個體來建立 BlueXP 邊緣快取架構。核心執行個體的設計是要引導分散式 BlueXP 邊緣快取 Edge 執行個體與資料中心檔案伺服器資源（例如檔案共用、資料夾和檔案）之間的流量傳輸。

當您設計 BlueXP 邊緣快取部署時、您需要判斷在規模、資源可用度和備援方面、哪些是適合您環境的。BlueXP 邊緣快取核心可透過下列方式部署：

* 獨立執行個體
* 負載分散式設計（冷待機）


請參閱 <<規模調整準則>> 若要瞭解每個組態可支援的 Edge 執行個體數目上限和使用者總數：

請諮詢 NetApp 解決方案工程師、以討論企業部署的最佳選項。



== 規模調整準則

在設定初始系統時、您需要謹記幾種規模調整準則比率。在累積使用記錄後、您應該重新檢視這些比率、以確保您以最佳方式使用系統。包括：

* 邊緣 / 核心比率
* 分散式使用者 / 邊緣比例
* 分散式使用者 / 核心比率




=== 每個核心執行個體的 Edge 執行個體數

我們的準則建議每個 BlueXP 邊緣快取核心執行個體最多 10 個 Edge 執行個體、每個 BlueXP 邊緣快取核心執行個體最多 20 個邊緣。這在相當程度上取決於最常見工作負載的類型和平均檔案大小。在某些情況下、由於工作負載較為常見、您可以在每個核心新增更多Edge執行個體、但在這些情況下、您應該聯絡客戶代表、以判斷如何根據檔案集的類型和大小、正確調整Edge和Core執行個體的大小。


NOTE: 您可以同時運用多個 BlueXP 邊緣快取邊緣和核心執行個體、根據需求來擴充基礎架構。



=== 每個 Edge 執行個體的並行使用者數

BlueXP 邊緣快取邊緣在快取演算法和檔案層級差異方面處理繁重的工作。單一 Edge 執行個體每個專屬的 _Physical Edge 執行個體最多可服務 500 位使用者、而專屬的 _virtual _ 部署最多可服務 300 位使用者。這在相當程度上取決於最常見工作負載的類型和平均檔案大小。對於較大型的協同作業檔案類型、請根據 BlueXP 邊緣快取邊緣較低界限（視實體或虛擬部署而定）、引導使用者達到最高使用者人數的 50% 。若為平均檔案大小 <1MB 的較常見 Office 項目、請引導每個 Edge 上限的 100% 使用者（視實體或虛擬部署而定）。


NOTE: BlueXP 邊緣快取邊緣會偵測它是在虛擬或實體執行個體上執行、並將本機虛擬檔案共用的 SMB 連線數量限制為最多 300 或 500 個並行連線。



=== 每個核心執行個體的並行使用者數

BlueXP 邊緣快取核心執行個體具有極高的擴充性、建議每個核心同時使用者數為 3 、 000 名。這在相當程度上取決於最常見工作負載的類型和平均檔案大小。

請諮詢 NetApp 解決方案工程師、以討論企業部署的最佳選項。



== 先決條件

本節所述的先決條件適用於安裝在雲端的元件： BlueXP 邊緣快取管理伺服器和 BlueXP 邊緣快取核心。

BlueXP 邊緣快取 Edge 先決條件說明如下： link:download-gfFC-edues.html#bluexp-edge 快取 -edge 需求 [ 此處 ] 。



=== 儲存平台（ Volume ）

後端儲存平台Cloud Volumes ONTAP （在此案例中為您部署的實例）應呈現SMB檔案共用。透過 BlueXP 邊緣快取所公開的任何共享區、都必須允許「 Everyone 」群組在共用層級進行「完全控制」、同時透過 NTFS 權限來限制權限。

如果 Cloud Volumes ONTAP 您尚未在這個例子上設定至少一個 SMB 檔案共用區、則需要準備好下列資訊、以便在安裝期間設定這些資訊：

* Active Directory 網域名稱、名稱伺服器 IP 位址、 Active Directory 管理認證。
* 您要建立的磁碟區名稱和大小、要建立磁碟區的集合體名稱、以及共用名稱。


我們建議磁碟區的大小足以容納應用程式的總資料集、並能隨著資料集的成長而隨之擴充。如果工作環境中有多個集合體、請參閱 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-aggregates.html["管理現有的集合體"^] 以判斷哪些 Aggregate 具有最大的可用空間、以供新磁碟區使用。



=== BlueXP 邊緣快取管理伺服器

BlueXP 邊緣快取管理伺服器需要透過 HTTPS （ TCP 連接埠 443 ）進行外部存取、才能連線至雲端供應商訂閱服務並存取以下 URL ：

* \https://gfcproxyforcm-prod.azurewebsites.net/
* \https://rest.zuora.com/v1/subscriptions/
* \https://rest.zuora.com/oauth/token
* \https://talonazuremicroservices.azurewebsites.net
* \https://talonlicensing.table.core.windows.net


必須將此連接埠排除在任何 WAN 最佳化裝置或防火牆限制原則之外、才能讓 BlueXP 邊緣快取軟體正常運作。

BlueXP 邊緣快取管理伺服器也需要執行個體的唯一（地理） NetBIOS 名稱（例如 GFC-MS1 ）。


NOTE: 單一管理伺服器可支援部署在不同工作環境中的多個 BlueXP 邊緣快取核心執行個體。從BlueXP部署時、每個工作環境都有各自獨立的後端儲存設備、而且不會包含相同的資料。



=== BlueXP 邊緣快取核心

BlueXP 邊際快取核心會偵聽 TCP 連接埠範圍 6618-6630 。視防火牆或網路安全群組（ NSG ）組態而定、您可能需要透過「傳入連接埠規則」明確允許存取這些連接埠。此外、必須將這些連接埠排除在任何 WAN 最佳化裝置或防火牆限制原則之外、才能讓 BlueXP 邊緣快取軟體正常運作。

BlueXP 邊緣快取核心需求如下：

* 執行個體的唯一（地理） NetBios 名稱（例如 GFC-cor1 ）
* Active Directory 網域名稱
+
** 執行個體應加入 Active Directory 網域。
** 執行個體應在 BlueXP 邊緣快取特定組織單位（ OU ）中進行管理、並從繼承的公司 GPO 中排除。


* 服務帳戶。核心上的服務會以特定網域使用者帳戶執行。此帳戶也稱為「服務帳戶」、在與 BlueXP 邊際快取核心執行個體相關的每部 SMB 伺服器上、必須具有下列權限：
+
** 已配置的服務帳戶必須是網域使用者。
+
視網路環境中的限制層級和 GPO 而定、此帳戶可能需要網域管理員權限。

** IT 必須擁有「以服務形式執行」權限。
** 密碼應設定為「永不過期」。
** 帳戶選項「 User must Change Password at Next Logon" （使用者下次登入時必須變更密碼）應停用（取消核取）。
** 它必須是後端檔案伺服器內建Backup Operators群組的成員（透過BlueXP部署時會自動啟用此功能）。






=== 授權管理伺服器

* BlueXP 邊緣快取授權管理伺服器（ LMS ）應設定在 Microsoft Windows Server 2016 Standard 或 Datacenter 版或 Windows Server 2019 Standard 或 Datacenter 版上、最好是在資料中心或雲端的 BlueXP Edge 快取核心執行個體上。
* 如果您需要個別的 BlueXP 邊緣快取 LMS 執行個體、則需要在原始的 Microsoft Windows Server 執行個體上安裝最新的 BlueXP 邊緣快取軟體安裝套件。
* LMS執行個體必須能夠使用HTTPS（TCP連接埠443）連線至訂閱服務（公有網際網路）。
* 核心和 Edge 執行個體需要使用 HTTPS （ TCP 連接埠 443 ）連線至 LMS 執行個體。




=== 網路（外部存取）

BlueXP 邊緣快取 LMS 需要透過 HTTPS （ TCP 連接埠 443 ）外部存取下列 URL 。

* 如果您使用的是GFC訂閱型授權：
+
** \https://rest.zuora.com/v1/subscriptions/<subscription-no>
** \https://rest.zuora.com/oauth/token


* 如果您使用的是NetApp基於NSS-的授權：
+
** \https://login.netapp.com
** \https://login.netapp.com/ms_oauth/oauth2/endpoints
** \https://login.netapp.com/ms_oauth/oauth2/endpoints/oauthservice/tokens


* 如果您使用的是NetApp舊版授權：
+
** \https://talonazuremicroservices.azurewebsites.net
** \https://talonlicensing.table.core.windows.net






=== 網路

* 防火牆： BlueXP 邊緣快取邊緣和核心執行個體之間應允許 TCP 連接埠。
* BlueXP 邊緣快取 TCP 連接埠： 443 （ HTTPS ）、 6618-6630 。
* 網路最佳化裝置（例如 Riverbed Steelhead ）必須設定為通過 BlueXP 邊緣快取特定連接埠（ TCP 6618-6630 ）。

