---
settings:
  name: Global File Cache
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: zh-tw,us-en,ja-jp,ko-kr,zh-cn,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: 全域檔案快取文件
    url: "/index.html"
  - title: 版本資訊
    entries:
    - title: 新增功能
      url: "/whats-new.html"
    - title: 修正問題
      url: "/fixed-issues.html"
  - title: 開始使用
    entries:
    - title: 深入瞭解全域檔案快取
      url: "/concept-gfc.html"
    - title: 全域檔案快取先決條件
      url: "/concept-before-you-begin-to-deploy-gfc.html"
    - title: 部署及授權全域檔案快取
      url: "/task-gfc-getting-started.html"
    - title: 全域檔案快取Edge先決條件
      url: "/download-gfc-resources.html"
    - title: 部署全域檔案快取 Edge
      url: "/task-deploy-gfc-edge-instances.html"
  - title: 使用全域檔案快取
    entries:
    - title: 終端使用者訓練
      url: "/concept-gfc-enduser-training.html"
    - title: 其他資訊
      url: "/reference-gfc-additional-information.html"
  - title: 知識與支援
    entries:
    - title: 註冊以取得支援
      url: "/task-support-registration.html"
    - title: 取得協助
      url: "/task-get-help.html"
  - title: 法律聲明
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: 開始使用
    links:
    - title: 深入瞭解全域檔案快取
      url: concept-gfc.html
    - title: 新增功能
      url: whats-new.html
    - title: 限制
      url: concept-gfc.html#limitations
  - title: 部署元件
    links:
    - title: 部署Cloud Volumes ONTAP 以作為儲存平台的功能
      url: task-gfc-getting-started.html#deploy-cloud-volumes-ontap-as-your-storage-platform
    - title: 部署全域檔案快取管理伺服器和全域檔案快取核心
      url: task-gfc-getting-started.html#enable-global-file-cache-in-your-working-environment
    - title: 部署全域檔案快取 Edge 執行個體
      url: task-deploy-gfc-edge-instances.html
  - title: 訓練使用者
    links:
    - title: 終端使用者訓練
      url: concept-gfc-enduser-training.html
  - title: 部落格社群
    links:
    - title: NetApp社群
      url: https://community.netapp.com/t5/BlueXP-and-Services/ct-p/CDS
    - title: BlueXP部落格
      url: https://bluexp.netapp.com/blog
    - title: 雲端網路研討會
      url: https://bluexp.netapp.com/events
  - title: 其他資源
    links:
    - title: BlueXP Edge 快取使用案例
      url: https://bluexp.netapp.com/global-file-cache
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: 所有BlueXP文件
