---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, gfc, global file cache' 
summary: 瞭解 BlueXP 邊緣快取的新功能。 
---
= BlueXP 邊緣快取的新功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
瞭解 BlueXP 邊緣快取的新功能。



== 2024 年 5 月 6 日（ 2.4 版）

此版本可修正一些小問題。更新的軟體套件可在以下網址取得： https://docs.netapp.com/us-en/bluexp-edge-caching/download-gfc-resources.html#download-required-resources["本頁"]。



== 2023 年 8 月 1 日（ 2.3 版）

此版本可修正中所述的問題 https://docs.netapp.com/us-en/bluexp-edge-caching/fixed-issues.html["修正問題"]。如需更新的軟體套件、請參閱 https://docs.netapp.com/us-en/bluexp-edge-caching/download-gfc-resources.html#download-required-resources["本頁"]。



== 2023 年 4 月 5 日（ 2.2 版）

此版本提供下列新功能。也可修正中所述的問題 https://docs.netapp.com/us-en/bluexp-edge-caching/fixed-issues.html["修正問題"]。



=== 在部署於 Google Cloud 的 Cloud Volumes ONTAP 系統上支援 Global File Cache

在 Google Cloud 中部署 Cloud Volumes ONTAP 系統時、可使用新的「邊緣快取」授權。您有權在 Cloud Volumes ONTAP 系統上為每 3 TiB 購買容量部署一個全域檔案快取 Edge 系統。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html#packages["深入瞭解Edge Cache授權套件。"]



=== 設定精靈和 GFC 組態 UI 已增強、可執行 NetApp 授權登錄



=== 增強的 Optimus PSM 可設定 Edge Sync 功能



== 2022年10月24日（2.1版）

此版本提供下列新功能。也可修正中所述的問題 https://docs.netapp.com/us-en/bluexp-edge-caching/fixed-issues.html["修正問題"]。



=== 全域檔案快取現在可搭配任意數量的授權使用

先前的10份授權（即30 TB儲存容量）最低需求已移除。每3 TB儲存空間將會核發一份全域檔案快取授權。



=== 已新增使用離線授權管理伺服器的支援

當LMS沒有網際網路連線、無法使用授權來源進行授權驗證時、離線或暗線站台的授權管理伺服器（LMS）最有用。初始組態期間需要網際網路連線和授權來源連線。設定完成後、LMS執行個體可能變暗。所有邊緣/核心都應與LMS建立連線、以持續驗證授權。



=== Edge執行個體可支援其他並行使用者

單一Global File Cache Edge執行個體可為每個專屬的實體Edge執行個體提供最多500位使用者的服務、以及最多300位使用者的專屬虛擬部署服務。使用者人數上限分別為400和200。



=== 增強的Optimus PSM可設定雲端授權



=== 強化Optimus UI（Edge組態）中的Edge Sync功能、以顯示所有連線的用戶端



== 2022年7月25日（2.0版）

此版本提供下列新功能。也可修正中所述的問題 https://docs.netapp.com/us-en/bluexp-edge-caching/fixed-issues.html["修正問題"]。



=== 全新的容量型授權模式、透過Azure Marketplace提供全域檔案快取功能

新的「Edge Cache」授權與「CVO Professional」授權具有相同的功能、但也支援全域檔案快取。在Cloud Volumes ONTAP Azure中部署全新的功能完善的更新版時、您會看到這個選項。您有權在Cloud Volumes ONTAP 整個作業系統上、為3個已配置容量的TiB部署一個Global File Cache Edge系統。至少應配置30個TiB。GFC授權管理程式服務已經過強化、可提供容量型授權。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html#capacity-based-licensing["深入瞭解Edge Cache授權套件。"]



=== 全域檔案快取現在已整合Cloud Insights 至功能性

NetApp Cloud Insights 產品（CI）可讓您完整掌握基礎架構與應用程式。現在、全域檔案快取已與CI整合、提供所有邊緣和核心的完整可見度；監控執行個體上執行的程序。將各種「全域檔案快取」指標推送至CI、以提供CI儀表板的完整總覽。請參閱的第11章 https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.1.0%20User%20Guide.pdf["NetApp 全球檔案快取使用者指南"^]

https://cloud.netapp.com/cloud-insights["深入瞭Cloud Insights 解功能。"]



=== 授權管理伺服器已經過強化、可在極具限制的環境中運作

在授權組態期間、授權管理伺服器（LMS）應可存取網際網路、以便向NetApp/期望職位收集授權詳細資料。一旦組態成功、LMS就能繼續以離線模式運作、並提供授權功能、即使在限制嚴格的環境中。



=== Optimus中的Edge Sync UI已增強功能、可在協調者Edge上顯示連線的用戶端清單
